/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ModelsIP;
import io.swagger.client.model.ModelsMember;
import io.swagger.client.model.ModelsSubAccount;
import io.swagger.client.model.ModelsTag;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ModelsIncident
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-27T05:08:14.940Z")



public class ModelsIncident {
  @SerializedName("author")
  private ModelsMember author = null;

  @SerializedName("created")
  private Long created = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("relatedIP")
  private ModelsIP relatedIP = null;

  @SerializedName("relatedSubAccount")
  private ModelsSubAccount relatedSubAccount = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("summary")
  private String summary = null;

  @SerializedName("tags")
  private List<ModelsTag> tags = null;

  @SerializedName("updated")
  private Long updated = null;

  public ModelsIncident author(ModelsMember author) {
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @ApiModelProperty(value = "")
  public ModelsMember getAuthor() {
    return author;
  }

  public void setAuthor(ModelsMember author) {
    this.author = author;
  }

  public ModelsIncident created(Long created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public Long getCreated() {
    return created;
  }

  public void setCreated(Long created) {
    this.created = created;
  }

  public ModelsIncident description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ModelsIncident id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ModelsIncident relatedIP(ModelsIP relatedIP) {
    this.relatedIP = relatedIP;
    return this;
  }

   /**
   * Get relatedIP
   * @return relatedIP
  **/
  @ApiModelProperty(value = "")
  public ModelsIP getRelatedIP() {
    return relatedIP;
  }

  public void setRelatedIP(ModelsIP relatedIP) {
    this.relatedIP = relatedIP;
  }

  public ModelsIncident relatedSubAccount(ModelsSubAccount relatedSubAccount) {
    this.relatedSubAccount = relatedSubAccount;
    return this;
  }

   /**
   * Get relatedSubAccount
   * @return relatedSubAccount
  **/
  @ApiModelProperty(value = "")
  public ModelsSubAccount getRelatedSubAccount() {
    return relatedSubAccount;
  }

  public void setRelatedSubAccount(ModelsSubAccount relatedSubAccount) {
    this.relatedSubAccount = relatedSubAccount;
  }

  public ModelsIncident status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public ModelsIncident summary(String summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @ApiModelProperty(value = "")
  public String getSummary() {
    return summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }

  public ModelsIncident tags(List<ModelsTag> tags) {
    this.tags = tags;
    return this;
  }

  public ModelsIncident addTagsItem(ModelsTag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<ModelsTag>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public List<ModelsTag> getTags() {
    return tags;
  }

  public void setTags(List<ModelsTag> tags) {
    this.tags = tags;
  }

  public ModelsIncident updated(Long updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  @ApiModelProperty(value = "")
  public Long getUpdated() {
    return updated;
  }

  public void setUpdated(Long updated) {
    this.updated = updated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsIncident modelsIncident = (ModelsIncident) o;
    return Objects.equals(this.author, modelsIncident.author) &&
        Objects.equals(this.created, modelsIncident.created) &&
        Objects.equals(this.description, modelsIncident.description) &&
        Objects.equals(this.id, modelsIncident.id) &&
        Objects.equals(this.relatedIP, modelsIncident.relatedIP) &&
        Objects.equals(this.relatedSubAccount, modelsIncident.relatedSubAccount) &&
        Objects.equals(this.status, modelsIncident.status) &&
        Objects.equals(this.summary, modelsIncident.summary) &&
        Objects.equals(this.tags, modelsIncident.tags) &&
        Objects.equals(this.updated, modelsIncident.updated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(author, created, description, id, relatedIP, relatedSubAccount, status, summary, tags, updated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsIncident {\n");
    
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    relatedIP: ").append(toIndentedString(relatedIP)).append("\n");
    sb.append("    relatedSubAccount: ").append(toIndentedString(relatedSubAccount)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

