/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ModelsEIP;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ModelsEIPPool
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-06T12:08:13.160Z")



public class ModelsEIPPool {
  @SerializedName("ips")
  private List<ModelsEIP> ips = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("routingMapping")
  private Object routingMapping = null;

  @SerializedName("routingStrategy")
  private Long routingStrategy = null;

  public ModelsEIPPool ips(List<ModelsEIP> ips) {
    this.ips = ips;
    return this;
  }

  public ModelsEIPPool addIpsItem(ModelsEIP ipsItem) {
    if (this.ips == null) {
      this.ips = new ArrayList<ModelsEIP>();
    }
    this.ips.add(ipsItem);
    return this;
  }

   /**
   * Get ips
   * @return ips
  **/
  @ApiModelProperty(value = "")
  public List<ModelsEIP> getIps() {
    return ips;
  }

  public void setIps(List<ModelsEIP> ips) {
    this.ips = ips;
  }

  public ModelsEIPPool name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ModelsEIPPool routingMapping(Object routingMapping) {
    this.routingMapping = routingMapping;
    return this;
  }

   /**
   * Get routingMapping
   * @return routingMapping
  **/
  @ApiModelProperty(value = "")
  public Object getRoutingMapping() {
    return routingMapping;
  }

  public void setRoutingMapping(Object routingMapping) {
    this.routingMapping = routingMapping;
  }

  public ModelsEIPPool routingStrategy(Long routingStrategy) {
    this.routingStrategy = routingStrategy;
    return this;
  }

   /**
   * Get routingStrategy
   * @return routingStrategy
  **/
  @ApiModelProperty(value = "")
  public Long getRoutingStrategy() {
    return routingStrategy;
  }

  public void setRoutingStrategy(Long routingStrategy) {
    this.routingStrategy = routingStrategy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsEIPPool modelsEIPPool = (ModelsEIPPool) o;
    return Objects.equals(this.ips, modelsEIPPool.ips) &&
        Objects.equals(this.name, modelsEIPPool.name) &&
        Objects.equals(this.routingMapping, modelsEIPPool.routingMapping) &&
        Objects.equals(this.routingStrategy, modelsEIPPool.routingStrategy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ips, name, routingMapping, routingStrategy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsEIPPool {\n");
    
    sb.append("    ips: ").append(toIndentedString(ips)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    routingMapping: ").append(toIndentedString(routingMapping)).append("\n");
    sb.append("    routingStrategy: ").append(toIndentedString(routingStrategy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

