/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ModelsBackOffDecreaseType;
import java.io.IOException;

/**
 * ModelsBackOffConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-10-28T07:50:19.455Z")



public class ModelsBackOffConfiguration {
  @SerializedName("concurrentConnections")
  private Long concurrentConnections = null;

  @SerializedName("concurrentConnectionsType")
  private ModelsBackOffDecreaseType concurrentConnectionsType = null;

  @SerializedName("sendPerDay")
  private Long sendPerDay = null;

  @SerializedName("sendPerDayType")
  private ModelsBackOffDecreaseType sendPerDayType = null;

  @SerializedName("sendPerHour")
  private Long sendPerHour = null;

  @SerializedName("sendPerHourType")
  private ModelsBackOffDecreaseType sendPerHourType = null;

  @SerializedName("sendPerMinute")
  private Long sendPerMinute = null;

  @SerializedName("sendPerMinuteType")
  private ModelsBackOffDecreaseType sendPerMinuteType = null;

  public ModelsBackOffConfiguration concurrentConnections(Long concurrentConnections) {
    this.concurrentConnections = concurrentConnections;
    return this;
  }

   /**
   * Get concurrentConnections
   * @return concurrentConnections
  **/
  @ApiModelProperty(value = "")
  public Long getConcurrentConnections() {
    return concurrentConnections;
  }

  public void setConcurrentConnections(Long concurrentConnections) {
    this.concurrentConnections = concurrentConnections;
  }

  public ModelsBackOffConfiguration concurrentConnectionsType(ModelsBackOffDecreaseType concurrentConnectionsType) {
    this.concurrentConnectionsType = concurrentConnectionsType;
    return this;
  }

   /**
   * Get concurrentConnectionsType
   * @return concurrentConnectionsType
  **/
  @ApiModelProperty(value = "")
  public ModelsBackOffDecreaseType getConcurrentConnectionsType() {
    return concurrentConnectionsType;
  }

  public void setConcurrentConnectionsType(ModelsBackOffDecreaseType concurrentConnectionsType) {
    this.concurrentConnectionsType = concurrentConnectionsType;
  }

  public ModelsBackOffConfiguration sendPerDay(Long sendPerDay) {
    this.sendPerDay = sendPerDay;
    return this;
  }

   /**
   * Get sendPerDay
   * @return sendPerDay
  **/
  @ApiModelProperty(value = "")
  public Long getSendPerDay() {
    return sendPerDay;
  }

  public void setSendPerDay(Long sendPerDay) {
    this.sendPerDay = sendPerDay;
  }

  public ModelsBackOffConfiguration sendPerDayType(ModelsBackOffDecreaseType sendPerDayType) {
    this.sendPerDayType = sendPerDayType;
    return this;
  }

   /**
   * Get sendPerDayType
   * @return sendPerDayType
  **/
  @ApiModelProperty(value = "")
  public ModelsBackOffDecreaseType getSendPerDayType() {
    return sendPerDayType;
  }

  public void setSendPerDayType(ModelsBackOffDecreaseType sendPerDayType) {
    this.sendPerDayType = sendPerDayType;
  }

  public ModelsBackOffConfiguration sendPerHour(Long sendPerHour) {
    this.sendPerHour = sendPerHour;
    return this;
  }

   /**
   * Get sendPerHour
   * @return sendPerHour
  **/
  @ApiModelProperty(value = "")
  public Long getSendPerHour() {
    return sendPerHour;
  }

  public void setSendPerHour(Long sendPerHour) {
    this.sendPerHour = sendPerHour;
  }

  public ModelsBackOffConfiguration sendPerHourType(ModelsBackOffDecreaseType sendPerHourType) {
    this.sendPerHourType = sendPerHourType;
    return this;
  }

   /**
   * Get sendPerHourType
   * @return sendPerHourType
  **/
  @ApiModelProperty(value = "")
  public ModelsBackOffDecreaseType getSendPerHourType() {
    return sendPerHourType;
  }

  public void setSendPerHourType(ModelsBackOffDecreaseType sendPerHourType) {
    this.sendPerHourType = sendPerHourType;
  }

  public ModelsBackOffConfiguration sendPerMinute(Long sendPerMinute) {
    this.sendPerMinute = sendPerMinute;
    return this;
  }

   /**
   * Get sendPerMinute
   * @return sendPerMinute
  **/
  @ApiModelProperty(value = "")
  public Long getSendPerMinute() {
    return sendPerMinute;
  }

  public void setSendPerMinute(Long sendPerMinute) {
    this.sendPerMinute = sendPerMinute;
  }

  public ModelsBackOffConfiguration sendPerMinuteType(ModelsBackOffDecreaseType sendPerMinuteType) {
    this.sendPerMinuteType = sendPerMinuteType;
    return this;
  }

   /**
   * Get sendPerMinuteType
   * @return sendPerMinuteType
  **/
  @ApiModelProperty(value = "")
  public ModelsBackOffDecreaseType getSendPerMinuteType() {
    return sendPerMinuteType;
  }

  public void setSendPerMinuteType(ModelsBackOffDecreaseType sendPerMinuteType) {
    this.sendPerMinuteType = sendPerMinuteType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsBackOffConfiguration modelsBackOffConfiguration = (ModelsBackOffConfiguration) o;
    return Objects.equals(this.concurrentConnections, modelsBackOffConfiguration.concurrentConnections) &&
        Objects.equals(this.concurrentConnectionsType, modelsBackOffConfiguration.concurrentConnectionsType) &&
        Objects.equals(this.sendPerDay, modelsBackOffConfiguration.sendPerDay) &&
        Objects.equals(this.sendPerDayType, modelsBackOffConfiguration.sendPerDayType) &&
        Objects.equals(this.sendPerHour, modelsBackOffConfiguration.sendPerHour) &&
        Objects.equals(this.sendPerHourType, modelsBackOffConfiguration.sendPerHourType) &&
        Objects.equals(this.sendPerMinute, modelsBackOffConfiguration.sendPerMinute) &&
        Objects.equals(this.sendPerMinuteType, modelsBackOffConfiguration.sendPerMinuteType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(concurrentConnections, concurrentConnectionsType, sendPerDay, sendPerDayType, sendPerHour, sendPerHourType, sendPerMinute, sendPerMinuteType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsBackOffConfiguration {\n");
    
    sb.append("    concurrentConnections: ").append(toIndentedString(concurrentConnections)).append("\n");
    sb.append("    concurrentConnectionsType: ").append(toIndentedString(concurrentConnectionsType)).append("\n");
    sb.append("    sendPerDay: ").append(toIndentedString(sendPerDay)).append("\n");
    sb.append("    sendPerDayType: ").append(toIndentedString(sendPerDayType)).append("\n");
    sb.append("    sendPerHour: ").append(toIndentedString(sendPerHour)).append("\n");
    sb.append("    sendPerHourType: ").append(toIndentedString(sendPerHourType)).append("\n");
    sb.append("    sendPerMinute: ").append(toIndentedString(sendPerMinute)).append("\n");
    sb.append("    sendPerMinuteType: ").append(toIndentedString(sendPerMinuteType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

