/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ModelsIPStat
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-27T05:08:14.940Z")



public class ModelsIPStat {
  @SerializedName("clicked")
  private Long clicked = null;

  @SerializedName("day")
  private Long day = null;

  @SerializedName("delivered")
  private Long delivered = null;

  @SerializedName("dropped")
  private Long dropped = null;

  @SerializedName("hardBounced")
  private Long hardBounced = null;

  @SerializedName("month")
  private Long month = null;

  @SerializedName("opened")
  private Long opened = null;

  @SerializedName("processed")
  private Long processed = null;

  @SerializedName("softBounced")
  private Long softBounced = null;

  @SerializedName("spam")
  private Long spam = null;

  @SerializedName("unsubscribed")
  private Long unsubscribed = null;

  @SerializedName("year")
  private Long year = null;

  public ModelsIPStat clicked(Long clicked) {
    this.clicked = clicked;
    return this;
  }

   /**
   * Get clicked
   * @return clicked
  **/
  @ApiModelProperty(value = "")
  public Long getClicked() {
    return clicked;
  }

  public void setClicked(Long clicked) {
    this.clicked = clicked;
  }

  public ModelsIPStat day(Long day) {
    this.day = day;
    return this;
  }

   /**
   * Get day
   * @return day
  **/
  @ApiModelProperty(value = "")
  public Long getDay() {
    return day;
  }

  public void setDay(Long day) {
    this.day = day;
  }

  public ModelsIPStat delivered(Long delivered) {
    this.delivered = delivered;
    return this;
  }

   /**
   * Get delivered
   * @return delivered
  **/
  @ApiModelProperty(value = "")
  public Long getDelivered() {
    return delivered;
  }

  public void setDelivered(Long delivered) {
    this.delivered = delivered;
  }

  public ModelsIPStat dropped(Long dropped) {
    this.dropped = dropped;
    return this;
  }

   /**
   * Get dropped
   * @return dropped
  **/
  @ApiModelProperty(value = "")
  public Long getDropped() {
    return dropped;
  }

  public void setDropped(Long dropped) {
    this.dropped = dropped;
  }

  public ModelsIPStat hardBounced(Long hardBounced) {
    this.hardBounced = hardBounced;
    return this;
  }

   /**
   * Get hardBounced
   * @return hardBounced
  **/
  @ApiModelProperty(value = "")
  public Long getHardBounced() {
    return hardBounced;
  }

  public void setHardBounced(Long hardBounced) {
    this.hardBounced = hardBounced;
  }

  public ModelsIPStat month(Long month) {
    this.month = month;
    return this;
  }

   /**
   * Get month
   * @return month
  **/
  @ApiModelProperty(value = "")
  public Long getMonth() {
    return month;
  }

  public void setMonth(Long month) {
    this.month = month;
  }

  public ModelsIPStat opened(Long opened) {
    this.opened = opened;
    return this;
  }

   /**
   * Get opened
   * @return opened
  **/
  @ApiModelProperty(value = "")
  public Long getOpened() {
    return opened;
  }

  public void setOpened(Long opened) {
    this.opened = opened;
  }

  public ModelsIPStat processed(Long processed) {
    this.processed = processed;
    return this;
  }

   /**
   * Get processed
   * @return processed
  **/
  @ApiModelProperty(value = "")
  public Long getProcessed() {
    return processed;
  }

  public void setProcessed(Long processed) {
    this.processed = processed;
  }

  public ModelsIPStat softBounced(Long softBounced) {
    this.softBounced = softBounced;
    return this;
  }

   /**
   * Get softBounced
   * @return softBounced
  **/
  @ApiModelProperty(value = "")
  public Long getSoftBounced() {
    return softBounced;
  }

  public void setSoftBounced(Long softBounced) {
    this.softBounced = softBounced;
  }

  public ModelsIPStat spam(Long spam) {
    this.spam = spam;
    return this;
  }

   /**
   * Get spam
   * @return spam
  **/
  @ApiModelProperty(value = "")
  public Long getSpam() {
    return spam;
  }

  public void setSpam(Long spam) {
    this.spam = spam;
  }

  public ModelsIPStat unsubscribed(Long unsubscribed) {
    this.unsubscribed = unsubscribed;
    return this;
  }

   /**
   * Get unsubscribed
   * @return unsubscribed
  **/
  @ApiModelProperty(value = "")
  public Long getUnsubscribed() {
    return unsubscribed;
  }

  public void setUnsubscribed(Long unsubscribed) {
    this.unsubscribed = unsubscribed;
  }

  public ModelsIPStat year(Long year) {
    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @ApiModelProperty(value = "")
  public Long getYear() {
    return year;
  }

  public void setYear(Long year) {
    this.year = year;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsIPStat modelsIPStat = (ModelsIPStat) o;
    return Objects.equals(this.clicked, modelsIPStat.clicked) &&
        Objects.equals(this.day, modelsIPStat.day) &&
        Objects.equals(this.delivered, modelsIPStat.delivered) &&
        Objects.equals(this.dropped, modelsIPStat.dropped) &&
        Objects.equals(this.hardBounced, modelsIPStat.hardBounced) &&
        Objects.equals(this.month, modelsIPStat.month) &&
        Objects.equals(this.opened, modelsIPStat.opened) &&
        Objects.equals(this.processed, modelsIPStat.processed) &&
        Objects.equals(this.softBounced, modelsIPStat.softBounced) &&
        Objects.equals(this.spam, modelsIPStat.spam) &&
        Objects.equals(this.unsubscribed, modelsIPStat.unsubscribed) &&
        Objects.equals(this.year, modelsIPStat.year);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clicked, day, delivered, dropped, hardBounced, month, opened, processed, softBounced, spam, unsubscribed, year);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsIPStat {\n");
    
    sb.append("    clicked: ").append(toIndentedString(clicked)).append("\n");
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    delivered: ").append(toIndentedString(delivered)).append("\n");
    sb.append("    dropped: ").append(toIndentedString(dropped)).append("\n");
    sb.append("    hardBounced: ").append(toIndentedString(hardBounced)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    opened: ").append(toIndentedString(opened)).append("\n");
    sb.append("    processed: ").append(toIndentedString(processed)).append("\n");
    sb.append("    softBounced: ").append(toIndentedString(softBounced)).append("\n");
    sb.append("    spam: ").append(toIndentedString(spam)).append("\n");
    sb.append("    unsubscribed: ").append(toIndentedString(unsubscribed)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

