/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ModelsGlockappsMonitorStat;
import java.io.IOException;

/**
 * ModelsRGlockappsMonitorStat
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-27T05:08:14.940Z")



public class ModelsRGlockappsMonitorStat {
  @SerializedName("date")
  private String date = null;

  @SerializedName("stat")
  private ModelsGlockappsMonitorStat stat = null;

  public ModelsRGlockappsMonitorStat date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public ModelsRGlockappsMonitorStat stat(ModelsGlockappsMonitorStat stat) {
    this.stat = stat;
    return this;
  }

   /**
   * Get stat
   * @return stat
  **/
  @ApiModelProperty(value = "")
  public ModelsGlockappsMonitorStat getStat() {
    return stat;
  }

  public void setStat(ModelsGlockappsMonitorStat stat) {
    this.stat = stat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsRGlockappsMonitorStat modelsRGlockappsMonitorStat = (ModelsRGlockappsMonitorStat) o;
    return Objects.equals(this.date, modelsRGlockappsMonitorStat.date) &&
        Objects.equals(this.stat, modelsRGlockappsMonitorStat.stat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, stat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsRGlockappsMonitorStat {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    stat: ").append(toIndentedString(stat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

