/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ModelsGlockappsBlacklist
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-06T12:27:02.903Z")



public class ModelsGlockappsBlacklist {
  @SerializedName("server")
  private String server = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("txt")
  private String txt = null;

  public ModelsGlockappsBlacklist server(String server) {
    this.server = server;
    return this;
  }

   /**
   * Get server
   * @return server
  **/
  @ApiModelProperty(value = "")
  public String getServer() {
    return server;
  }

  public void setServer(String server) {
    this.server = server;
  }

  public ModelsGlockappsBlacklist status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public ModelsGlockappsBlacklist txt(String txt) {
    this.txt = txt;
    return this;
  }

   /**
   * Get txt
   * @return txt
  **/
  @ApiModelProperty(value = "")
  public String getTxt() {
    return txt;
  }

  public void setTxt(String txt) {
    this.txt = txt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsGlockappsBlacklist modelsGlockappsBlacklist = (ModelsGlockappsBlacklist) o;
    return Objects.equals(this.server, modelsGlockappsBlacklist.server) &&
        Objects.equals(this.status, modelsGlockappsBlacklist.status) &&
        Objects.equals(this.txt, modelsGlockappsBlacklist.txt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(server, status, txt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsGlockappsBlacklist {\n");
    
    sb.append("    server: ").append(toIndentedString(server)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    txt: ").append(toIndentedString(txt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

