/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ModelsIP;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ModelsInstance
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-06T12:27:02.903Z")



public class ModelsInstance {
  @SerializedName("created")
  private Long created = null;

  @SerializedName("endpoint")
  private String endpoint = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("ips")
  private List<ModelsIP> ips = null;

  @SerializedName("name")
  private String name = null;

  public ModelsInstance created(Long created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public Long getCreated() {
    return created;
  }

  public void setCreated(Long created) {
    this.created = created;
  }

  public ModelsInstance endpoint(String endpoint) {
    this.endpoint = endpoint;
    return this;
  }

   /**
   * Get endpoint
   * @return endpoint
  **/
  @ApiModelProperty(value = "")
  public String getEndpoint() {
    return endpoint;
  }

  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }

  public ModelsInstance id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ModelsInstance ips(List<ModelsIP> ips) {
    this.ips = ips;
    return this;
  }

  public ModelsInstance addIpsItem(ModelsIP ipsItem) {
    if (this.ips == null) {
      this.ips = new ArrayList<ModelsIP>();
    }
    this.ips.add(ipsItem);
    return this;
  }

   /**
   * Get ips
   * @return ips
  **/
  @ApiModelProperty(value = "")
  public List<ModelsIP> getIps() {
    return ips;
  }

  public void setIps(List<ModelsIP> ips) {
    this.ips = ips;
  }

  public ModelsInstance name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsInstance modelsInstance = (ModelsInstance) o;
    return Objects.equals(this.created, modelsInstance.created) &&
        Objects.equals(this.endpoint, modelsInstance.endpoint) &&
        Objects.equals(this.id, modelsInstance.id) &&
        Objects.equals(this.ips, modelsInstance.ips) &&
        Objects.equals(this.name, modelsInstance.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, endpoint, id, ips, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsInstance {\n");
    
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ips: ").append(toIndentedString(ips)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

