/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ModelsCountStat;
import io.swagger.client.model.ModelsDeleteResponse;
import io.swagger.client.model.ModelsLabel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountlabelApi
 */
@Ignore
public class AccountlabelApiTest {

    private final AccountlabelApi api = new AccountlabelApi();

    
    /**
     * 
     *
     * Count Total Labels
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void labelRouterCountTest() throws ApiException {
        String xAccountApiKey = null;
        ModelsCountStat response = api.labelRouterCount(xAccountApiKey);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Create Label
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void labelRouterCreateTest() throws ApiException {
        String xAccountApiKey = null;
        ModelsLabel body = null;
        ModelsLabel response = api.labelRouterCreate(xAccountApiKey, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Delete Label
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void labelRouterDeleteTest() throws ApiException {
        String xAccountApiKey = null;
        Long labelId = null;
        ModelsDeleteResponse response = api.labelRouterDelete(xAccountApiKey, labelId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Find Label by LabelId
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void labelRouterGetTest() throws ApiException {
        String xAccountApiKey = null;
        Long labelId = null;
        ModelsLabel response = api.labelRouterGet(xAccountApiKey, labelId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get All Labels
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void labelRouterGetAllTest() throws ApiException {
        String xAccountApiKey = null;
        List<ModelsLabel> response = api.labelRouterGetAll(xAccountApiKey);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Update Label
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void labelRouterUpdateTest() throws ApiException {
        String xAccountApiKey = null;
        Long labelId = null;
        ModelsLabel body = null;
        ModelsLabel response = api.labelRouterUpdate(xAccountApiKey, labelId, body);

        // TODO: test validations
    }
    
}
