/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Alert;
import io.swagger.client.model.ModelsAlert;
import io.swagger.client.model.ModelsAlertRequest;
import io.swagger.client.model.ModelsCountStat;
import io.swagger.client.model.ModelsDetailedAlert;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountalertApi
 */
@Ignore
public class AccountalertApiTest {

    private final AccountalertApi api = new AccountalertApi();

    
    /**
     * 
     *
     * Count Total Alerts for account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void alertRouterCountTest() throws ApiException {
        String xAccountApiKey = null;
        String search = null;
        ModelsCountStat response = api.alertRouterCount(xAccountApiKey, search);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * create an alert
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void alertRouterCreateAlertTest() throws ApiException {
        String xAccountApiKey = null;
        ModelsAlertRequest body = null;
        ModelsAlert response = api.alertRouterCreateAlert(xAccountApiKey, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get All Alerts
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void alertRouterGetAllTest() throws ApiException {
        String xAccountApiKey = null;
        Long offset = null;
        Long limit = null;
        String search = null;
        List<ModelsDetailedAlert> response = api.alertRouterGetAll(xAccountApiKey, offset, limit, search);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Update an Alert
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void alertRouterUpdateTest() throws ApiException {
        String xAccountApiKey = null;
        Long alertid = null;
        Alert body = null;
        Alert response = api.alertRouterUpdate(xAccountApiKey, alertid, body);

        // TODO: test validations
    }
    
}
