/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ModelsQEmailMessage;
import io.swagger.client.model.ModelsQEvent;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountmessageApi
 */
@Ignore
public class AccountmessageApiTest {

    private final AccountmessageApi api = new AccountmessageApi();

    
    /**
     * 
     *
     * Find Message By Id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void messageRouterGetTest() throws ApiException {
        String xAccountApiKey = null;
        String messageId = null;
        ModelsQEmailMessage response = api.messageRouterGet(xAccountApiKey, messageId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Find all events associated with a message id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void messageRouterGetAllEventsForAMessageIdTest() throws ApiException {
        String xAccountApiKey = null;
        String messageId = null;
        List<ModelsQEvent> response = api.messageRouterGetAllEventsForAMessageId(xAccountApiKey, messageId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Find all message events associated with a message id from a specific node
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void messageRouterGetAllEventsForAMessageIdFromANodeTest() throws ApiException {
        String xAccountApiKey = null;
        String messageId = null;
        List<ModelsQEvent> response = api.messageRouterGetAllEventsForAMessageIdFromANode(xAccountApiKey, messageId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Find Message from node by specific Id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void messageRouterGetMessageFromNodeTest() throws ApiException {
        String xAccountApiKey = null;
        String messageId = null;
        ModelsQEmailMessage response = api.messageRouterGetMessageFromNode(xAccountApiKey, messageId);

        // TODO: test validations
    }
    
}
