/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ModelsRStat;
import io.swagger.client.model.ModelsStat;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountstatApi
 */
@Ignore
public class AccountstatApiTest {

    private final AccountstatApi api = new AccountstatApi();

    
    /**
     * 
     *
     * Get All Account Stats
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accountStatRouterGetAllAccountStatsTest() throws ApiException {
        String xAccountApiKey = null;
        String from = null;
        String to = null;
        List<ModelsRStat> response = api.accountStatRouterGetAllAccountStats(xAccountApiKey, from, to);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get All Account Stats by Group
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accountStatRouterGetAllAccountStatsByGroupTest() throws ApiException {
        String xAccountApiKey = null;
        String group = null;
        String from = null;
        String to = null;
        List<ModelsRStat> response = api.accountStatRouterGetAllAccountStatsByGroup(xAccountApiKey, group, from, to);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get All Aggregate Stats
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accountStatRouterGetAllAggregateAccountStatsTest() throws ApiException {
        String xAccountApiKey = null;
        String from = null;
        String to = null;
        ModelsStat response = api.accountStatRouterGetAllAggregateAccountStats(xAccountApiKey, from, to);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get All Aggregate Stats by Group
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accountStatRouterGetAllAggregateAccountStatsByGroupTest() throws ApiException {
        String xAccountApiKey = null;
        String group = null;
        String from = null;
        String to = null;
        ModelsStat response = api.accountStatRouterGetAllAggregateAccountStatsByGroup(xAccountApiKey, group, from, to);

        // TODO: test validations
    }
    
}
