/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ModelsCountStat;
import io.swagger.client.model.ModelsDeleteResponse;
import io.swagger.client.model.ModelsIIP;
import io.swagger.client.model.ModelsIP;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountipApi
 */
@Ignore
public class AccountipApiTest {

    private final AccountipApi api = new AccountipApi();

    
    /**
     * 
     *
     * Allocate IP To Account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void iPRouterAllocateIPTest() throws ApiException {
        String xAccountApiKey = null;
        List<ModelsIP> response = api.iPRouterAllocateIP(xAccountApiKey);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Count Total AccountIPs
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void iPRouterCountTest() throws ApiException {
        String xAccountApiKey = null;
        String search = null;
        ModelsCountStat response = api.iPRouterCount(xAccountApiKey, search);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Delete IP
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void iPRouterDeleteTest() throws ApiException {
        String xAccountApiKey = null;
        Long ipid = null;
        ModelsDeleteResponse response = api.iPRouterDelete(xAccountApiKey, ipid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Find IP by IPId
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void iPRouterGetTest() throws ApiException {
        String xAccountApiKey = null;
        Long ipid = null;
        ModelsIP response = api.iPRouterGet(xAccountApiKey, ipid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get All IPs
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void iPRouterGetAllTest() throws ApiException {
        String xAccountApiKey = null;
        Long offset = null;
        Long limit = null;
        String search = null;
        List<ModelsIP> response = api.iPRouterGetAll(xAccountApiKey, offset, limit, search);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Update an IP
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void iPRouterUpdateTest() throws ApiException {
        String xAccountApiKey = null;
        Long ipid = null;
        ModelsIIP body = null;
        ModelsIP response = api.iPRouterUpdate(xAccountApiKey, ipid, body);

        // TODO: test validations
    }
    
}
