/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ModelsQEmailMessage;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountrecipientApi
 */
@Ignore
public class AccountrecipientApiTest {

    private final AccountrecipientApi api = new AccountrecipientApi();

    
    /**
     * 
     *
     * Find all messages sent to a specific recipient
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void recipientRouterGetAllMessagesForARecipientTest() throws ApiException {
        String xAccountApiKey = null;
        String recipient = null;
        List<ModelsQEmailMessage> response = api.recipientRouterGetAllMessagesForARecipient(xAccountApiKey, recipient);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Find all message sent to a recipient from a specific node
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void recipientRouterGetAllMessagesForARecipientFromANodeTest() throws ApiException {
        String xAccountApiKey = null;
        String recipient = null;
        List<ModelsQEmailMessage> response = api.recipientRouterGetAllMessagesForARecipientFromANode(xAccountApiKey, recipient);

        // TODO: test validations
    }
    
}
