/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ModelsDeleteResponse;
import io.swagger.client.model.ModelsMember;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountmemberApi
 */
@Ignore
public class AccountmemberApiTest {

    private final AccountmemberApi api = new AccountmemberApi();

    
    /**
     * 
     *
     * Delete Member
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void memberRouterDeleteTest() throws ApiException {
        String xAccountApiKey = null;
        Long memberId = null;
        ModelsDeleteResponse response = api.memberRouterDelete(xAccountApiKey, memberId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Find Member by MemberId
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void memberRouterGetTest() throws ApiException {
        String xAccountApiKey = null;
        Long memberId = null;
        ModelsMember response = api.memberRouterGet(xAccountApiKey, memberId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get All Members
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void memberRouterGetAllTest() throws ApiException {
        String xAccountApiKey = null;
        List<ModelsMember> response = api.memberRouterGetAll(xAccountApiKey);

        // TODO: test validations
    }
    
}
