/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClusterApi
 */
@Ignore
public class ClusterApiTest {

    private final ClusterApi api = new ClusterApi();

    
    /**
     * 
     *
     * Delete item from cache of every node in cluster
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void clusterRouterDeleteItemFromCacheOfEveryNodeInClusterTest() throws ApiException {
        String xSystemApiKey = null;
        String name = null;
        String key = null;
        api.clusterRouterDeleteItemFromCacheOfEveryNodeInCluster(xSystemApiKey, name, key);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Delete item from cache of specific node in cluster
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void clusterRouterDeleteItemFromCacheOfSpecificNodeInClusterTest() throws ApiException {
        String xSystemApiKey = null;
        String name = null;
        String key = null;
        api.clusterRouterDeleteItemFromCacheOfSpecificNodeInCluster(xSystemApiKey, name, key);

        // TODO: test validations
    }
    
}
