/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ModelsEditorTokenResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EditorApi
 */
@Ignore
public class EditorApiTest {

    private final EditorApi api = new EditorApi();

    
    /**
     * 
     *
     * fetch Bee editor token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editorApiRouterGetTokenTest() throws ApiException {
        String xAccountApiKey = null;
        ModelsEditorTokenResponse response = api.editorApiRouterGetToken(xAccountApiKey);

        // TODO: test validations
    }
    
}
