/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ModelsSystemTemplate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SystemApi
 */
@Ignore
public class SystemApiTest {

    private final SystemApi api = new SystemApi();

    
    /**
     * 
     *
     * Get all System Templates
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemTemplateRouterGetAllSystemTemplatesTest() throws ApiException {
        String xAccountApiKey = null;
        List<ModelsSystemTemplate> response = api.systemTemplateRouterGetAllSystemTemplates(xAccountApiKey);

        // TODO: test validations
    }
    
}
