/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TrackApi
 */
@Ignore
public class TrackApiTest {

    private final TrackApi api = new TrackApi();

    
    /**
     * 
     *
     * Track Email Open
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void trackRouterTrackEmailOpenTest() throws ApiException {
        Long ipId = null;
        Long accountId = null;
        Long subAccountId = null;
        String messageId = null;
        String emailType = null;
        api.trackRouterTrackEmailOpen(ipId, accountId, subAccountId, messageId, emailType);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Track Link Click
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void trackRouterTrackLinkClickTest() throws ApiException {
        Long ipId = null;
        Long accountId = null;
        Long subAccountId = null;
        String messageId = null;
        String emailType = null;
        String redirecturl = null;
        api.trackRouterTrackLinkClick(ipId, accountId, subAccountId, messageId, emailType, redirecturl);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * track link click
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void trackRouterTrackUnsubscribeTest() throws ApiException {
        Long ipId = null;
        Long accountId = null;
        Long subAccountId = null;
        String messageId = null;
        String emailType = null;
        api.trackRouterTrackUnsubscribe(ipId, accountId, subAccountId, messageId, emailType);

        // TODO: test validations
    }
    
}
