/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;



import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ClusterApi {
    private ApiClient apiClient;

    public ClusterApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ClusterApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for clusterRouterDeleteItemFromCacheOfEveryNodeInCluster
     * @param xSystemApiKey System API Key (required)
     * @param name cache name (optional)
     * @param key cache item key to delete (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call clusterRouterDeleteItemFromCacheOfEveryNodeInClusterCall(String xSystemApiKey, String name, String key, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/cluster/cache";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (name != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("name", name));
        if (key != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("key", key));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        if (xSystemApiKey != null)
        localVarHeaderParams.put("X-System-ApiKey", apiClient.parameterToString(xSystemApiKey));

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call clusterRouterDeleteItemFromCacheOfEveryNodeInClusterValidateBeforeCall(String xSystemApiKey, String name, String key, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'xSystemApiKey' is set
        if (xSystemApiKey == null) {
            throw new ApiException("Missing the required parameter 'xSystemApiKey' when calling clusterRouterDeleteItemFromCacheOfEveryNodeInCluster(Async)");
        }
        

        com.squareup.okhttp.Call call = clusterRouterDeleteItemFromCacheOfEveryNodeInClusterCall(xSystemApiKey, name, key, progressListener, progressRequestListener);
        return call;

    }

    /**
     * 
     * Delete item from cache of every node in cluster
     * @param xSystemApiKey System API Key (required)
     * @param name cache name (optional)
     * @param key cache item key to delete (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void clusterRouterDeleteItemFromCacheOfEveryNodeInCluster(String xSystemApiKey, String name, String key) throws ApiException {
        clusterRouterDeleteItemFromCacheOfEveryNodeInClusterWithHttpInfo(xSystemApiKey, name, key);
    }

    /**
     * 
     * Delete item from cache of every node in cluster
     * @param xSystemApiKey System API Key (required)
     * @param name cache name (optional)
     * @param key cache item key to delete (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> clusterRouterDeleteItemFromCacheOfEveryNodeInClusterWithHttpInfo(String xSystemApiKey, String name, String key) throws ApiException {
        com.squareup.okhttp.Call call = clusterRouterDeleteItemFromCacheOfEveryNodeInClusterValidateBeforeCall(xSystemApiKey, name, key, null, null);
        return apiClient.execute(call);
    }

    /**
     *  (asynchronously)
     * Delete item from cache of every node in cluster
     * @param xSystemApiKey System API Key (required)
     * @param name cache name (optional)
     * @param key cache item key to delete (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call clusterRouterDeleteItemFromCacheOfEveryNodeInClusterAsync(String xSystemApiKey, String name, String key, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = clusterRouterDeleteItemFromCacheOfEveryNodeInClusterValidateBeforeCall(xSystemApiKey, name, key, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /**
     * Build call for clusterRouterDeleteItemFromCacheOfSpecificNodeInCluster
     * @param xSystemApiKey System API Key (required)
     * @param name cache name (optional)
     * @param key cache item key to delete (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call clusterRouterDeleteItemFromCacheOfSpecificNodeInClusterCall(String xSystemApiKey, String name, String key, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/cluster/cache/node";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (name != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("name", name));
        if (key != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("key", key));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        if (xSystemApiKey != null)
        localVarHeaderParams.put("X-System-ApiKey", apiClient.parameterToString(xSystemApiKey));

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call clusterRouterDeleteItemFromCacheOfSpecificNodeInClusterValidateBeforeCall(String xSystemApiKey, String name, String key, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'xSystemApiKey' is set
        if (xSystemApiKey == null) {
            throw new ApiException("Missing the required parameter 'xSystemApiKey' when calling clusterRouterDeleteItemFromCacheOfSpecificNodeInCluster(Async)");
        }
        

        com.squareup.okhttp.Call call = clusterRouterDeleteItemFromCacheOfSpecificNodeInClusterCall(xSystemApiKey, name, key, progressListener, progressRequestListener);
        return call;

    }

    /**
     * 
     * Delete item from cache of specific node in cluster
     * @param xSystemApiKey System API Key (required)
     * @param name cache name (optional)
     * @param key cache item key to delete (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void clusterRouterDeleteItemFromCacheOfSpecificNodeInCluster(String xSystemApiKey, String name, String key) throws ApiException {
        clusterRouterDeleteItemFromCacheOfSpecificNodeInClusterWithHttpInfo(xSystemApiKey, name, key);
    }

    /**
     * 
     * Delete item from cache of specific node in cluster
     * @param xSystemApiKey System API Key (required)
     * @param name cache name (optional)
     * @param key cache item key to delete (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> clusterRouterDeleteItemFromCacheOfSpecificNodeInClusterWithHttpInfo(String xSystemApiKey, String name, String key) throws ApiException {
        com.squareup.okhttp.Call call = clusterRouterDeleteItemFromCacheOfSpecificNodeInClusterValidateBeforeCall(xSystemApiKey, name, key, null, null);
        return apiClient.execute(call);
    }

    /**
     *  (asynchronously)
     * Delete item from cache of specific node in cluster
     * @param xSystemApiKey System API Key (required)
     * @param name cache name (optional)
     * @param key cache item key to delete (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call clusterRouterDeleteItemFromCacheOfSpecificNodeInClusterAsync(String xSystemApiKey, String name, String key, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = clusterRouterDeleteItemFromCacheOfSpecificNodeInClusterValidateBeforeCall(xSystemApiKey, name, key, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
}
